world_address = "0x4e77dcdb72dba9954dce4ec5eb60e701afacf02394069172b3ea50bdea6bddd"
rpc = "https://api.cartridge.gg/x/starknet/sepolia"

[server]
http_cors_origins = ["*"]

[grpc]
optimistic = true

[sql]
historical = [
    "hashfront-GameCreated",
    "hashfront-GameStarted",
    "hashfront-PlayerJoined",
    "hashfront-UnitMoved",
    "hashfront-UnitAttacked",
    "hashfront-UnitDied",
    "hashfront-BuildingCaptured",
    "hashfront-UnitBuilt",
    "hashfront-TurnEnded",
    "hashfront-GameOver",
]

[[sql.model_indices]]
model_tag = "hashfront-Game"
fields = ["name"]

[[sql.model_indices]]
model_tag = "hashfront-PlayerState"
fields = ["address"]

[indexing]
world_block = 0
pending = true
pre_confirmed = true
polling_interval = 250
contracts = []

